[[redirects]]
  from = "/influencerpack"
  to = "https://docs.google.com/presentation/d/e/2PACX-1vSwZ60sYbMZYIQXBIROORuBHh7f2GG8T3BtMZNlAdEEU5oYvlsQWEATj8bK8pYsZw/pub?start=false&loop=false&delayms=3000"
  status = 200
  force = true
