---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: src/pages/index.mdx
  label: Home
- type: document
  path: src/pages/blog.mdx
  label: Blog listing
- type: directory
  path: src/pages/blog
  label: Blog posts
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: src/pages
  label: Pages
  create: all
  match: "{,!(blog)/**/}*"
  exclude: "{index,404}.mdx"
  templates:
  - page
- type: document
  path: src/pages/404.mdx
  label: 404 page
- type: heading
  label: Navigation
- type: document
  path: src/data/header.json
  label: Header
- type: document
  path: src/data/footer.json
  label: Footer
upload_dir: public/uploads
public_path: uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn install
  preview_docker_image: node:13.14.0
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run start -- --port 8000 --hostname 0.0.0.0
